apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
        - name: e-commerce
          image: demoregistrymadan.azurecr.io/ecommerce:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: e-commerce-service
spec:
  type: LoadBalancer
  selector:
    app: e-commerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


